name: "🐛 Bug Report"
description: Report a problem or unexpected behavior in the plugin.
title: "[BUG] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Minecraft and Plugin Version
      description: What Minecraft version and UltimateBackpacks version are you using?
      placeholder: "e.g. Paper 1.20.1, UltimateBackpacks v1.3.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Help us reproduce the issue.
      placeholder: |
        1. Use command ...
        2. Open GUI ...
        3. Place item ...
        4. Crash occurs
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Errors
      description: Paste any error messages here (from console or logs).
      render: shell
    validations:
      required: false
